### ISSUE TITLE
Add support for `:matches()`

### ISSUE THREAD

**Issue by Mottie** [clean-css/clean-css#1016]
### Environment

Using online demo in Chrome (Windows 10) v4.1.11 - https://jakubpawlowicz.github.io/clean-css/

### Configuration options

Default level 1 + Default level 2 enabled

### Input CSS

```css
:matches(header, footer) div {color: black;}
:matches(header, footer) span {color: black;}
```

### Actual output CSS

```css
:matches(header,footer) div{color:#000}:matches(header,footer) span{color:#000}
```

### Expected output CSS

```css
:matches(header,footer) div,:matches(header,footer) span{color:#000}
```

The [`:matches()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:matches) psuedo-class selector will replace `:any()`; although the behavior reported in this issue is the same using either.

**Comment by clshortfuse** [comment]
`:matches()` is gone. It's now `:is()`. Personally, I want to break out of SCSS and move to pure CSS with nesting. Hopefully we can use some preprocessing to downconvert nesting rules for older browsers or cross-convert for varying prefixes.

With this objective in mind, *as long as there are no specificity changes* we properly convert to older browsers.

For example:

````css
:is(.a, .b) div { color: red; } 
````css

Is the equivalent of

````css
.a div, .b div { color: red; }
````

Specifically, only IE11 has no partial support at for nesting, but if the conditions are right, can have rules rewritten. Others can use different prefixes. Right now browser support from https://caniuse.com/css-matches-pseudo shows that `-webkit-any():` and `is()` should be enough for all modern browsers with IE11, of course, requiring a rewrite. 

As for what can safely be rewritten, specificity is based on the highest level of the arguments inside the parentheses. That means `:is(header, footer)` can safely be rewritten. `:is(header, .class)` cannot.
