### ISSUE TITLE
compress inefficient use of unicode-range

### ISSUE THREAD

**Issue by loominade** [clean-css/clean-css#1030]
If an embedded font only contains characters used on certain pages, one wouldn't want to download it if its used on the current page. By defining the  [`unicode-range`](https://developer.mozilla.org/en-US/docs/Web/CSS/%40font-face/unicode-range) of a font in a `@font-face` description, this can be achieved. But writing down all the codepoints in a font creates a very long `unicode-range` definition that can be shorted by collapsing groups.

### Input CSS

```css
@font-face {
  font-family: 'Openmoji';
  unicode-range: U+F0A0, U+F0A1, U+F0A2, U+F0A3, U+F0A4, U+F0A5, U+F0A6, U+F0A7, U+F0A8, U+F0A9, U+F0AA, U+F0AB, U+F0AC, U+F0AD, U+F0AE, U+F0AF;
}
```

### Actual output CSS

_– no change –_

### Expected output CSS
```css
@font-face {
  font-family: 'Openmoji';
  unicode-range: U+F0A?;
}
```
