### ISSUE TITLE
BUG: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by bjornharvold** [clean-css/clean-css#1042]
### Environment

* clean-css version - `4.2.0`:
* node.js version - `10.7.0`:
* operating system: Mac High Sierra

### Configuration options

```
Angular CLI 6.1.2, Angular 6.1.1
```

### Error
The error is hidden because the error reporting code fails. looks to be an invalid animation issue in my 3rd party SCSS but I am not sure what it is. I will look deeper into my CSS but line break-up.js:566 needs fixing.

asset optimization node_modules/clean-css/lib/optimizer/level-2/properties/populate-components.js:30
          throw e;
          ^

TypeError: Cannot read property '0' of undefined
    at transition (./node_modules/clean-css/lib/optimizer/level-2/break-up.js:566:93)
    at Object.breakUp (./node_modules/clean-css/lib/optimizer/level-2/break-up.js:466:28)
    at populateComponents (./node_modules/clean-css/lib/optimizer/level-2/properties/populate-components.js:17:42)
    at optimizeProperties (./node_modules/clean-css/lib/optimizer/level-2/properties/optimize.js:19:3)
    at recursivelyOptimizeProperties (/Users/crash/git/traveliko/traveliko-spa/node_modules/clean-css/lib/optimizer/level-2/optimize.js:63:9)
    at recursivelyOptimizeProperties (./node_modules/clean-css/lib/optimizer/level-2/optimize.js:66:9)

**Comment by bjornharvold** [comment]
To follow up, this is where the error is being thrown:

@include transition-default (all, 0.2s, ease);

Which is in mixins:
```css
@mixin transition-default ($what: all, $length: 0.3s, $easing: "") {
    @if ($what == transform) {
        @if ($easing != "") {
            -moz-transition: -moz-transform $length $easing;
            -o-transition: -o-transform $length $easing;
            -webkit-transition: -webkit-transform $length $easing;
            -ms-transition: -ms-transform $length $easing;
            transition: transform $length $easing;
        } @else {
            -moz-transition: -moz-transform $length;
            -o-transition: -o-transform $length;
            -webkit-transition: -webkit-transform $length;
            -ms-transition: -ms-transform $length;
            transition: transform $length;
        }
    } @else {
        @if ($easing != "") {
            -moz-transition: $what $length $easing;
            -o-transition: $what $length $easing;
            -webkit-transition: $what $length $easing;
            -ms-transition: $what $length $easing;
            transition: $what $length $easing;
        } @else {
            -moz-transition: $what $length ease-in-out;
            -o-transition: $what $length ease-in-out;
            -webkit-transition: $what $length ease-in-out;
            -ms-transition: $what $length ease-in-out;
            transition: $what $length ease-in-out;
        }
    }
}
```

Any ideas?

**Comment by bjornharvold** [comment]
FYI, this worked before v4.2.0. It stopped working once I updated Angular CLI to 6.1.2, build-ng-packager: 0.7.2 and build-angular: 0.7.2

**Comment by bjornharvold** [comment]
I can also see that the 3rd party SCSS is using this mixin in many different places with different attributes without breaking. The only difference with it breaking here that I can see is that the breaking SCSS is in an @import of the main SCSS file. Everything else is the same.

**Comment by jakubpawlowicz** [comment]
Thanks @bjornharvold for a bug report - could you also share a CSS file (as transformed SCSS) so I can narrow it down?

**Comment by bjornharvold** [comment]
![img_2045](https://user-images.githubusercontent.com/641791/43813847-b90c2940-9af1-11e8-934b-785386c19691.JPG)
![img_2046](https://user-images.githubusercontent.com/641791/43813861-d362eae0-9af1-11e8-9c92-8af4bea98902.JPG)
![img_2047](https://user-images.githubusercontent.com/641791/43813862-d39d08a6-9af1-11e8-98c8-7aec8f61497e.JPG)
![img_2048](https://user-images.githubusercontent.com/641791/43813863-d3d1011a-9af1-11e8-91bc-1199dcc5a267.JPG)
![img_2049](https://user-images.githubusercontent.com/641791/43813864-d4020ae4-9af1-11e8-8468-22f6ed662b7e.JPG)
![img_2050](https://user-images.githubusercontent.com/641791/43813866-d431dbd4-9af1-11e8-994a-c092ba1d13fd.JPG)
![img_2051](https://user-images.githubusercontent.com/641791/43813867-d463b140-9af1-11e8-8e4e-2440a2373540.JPG)

Just because I am not sure how to access this any other way :-)

**Comment by bjornharvold** [comment]
Uploaded sequentially. Sry Github rotated the pics.

**Comment by bjornharvold** [comment]
The issue is when this css is applied to the main-menu. 

SCSS all about the main menu - You can see where I commented out because clean-css failed there.
```css
@import 'styles/variables';
@import 'styles/mixin';


/* All styles for screen size over 992px
================================================== */
@media only screen and (min-width: 992px) {

	nav#menu.main-menu {
		display: block !important;
	}
	#mm-menu.main-menu {
		display: none !important;
	}
	header .btn_mobile {
		display: none !important;
	}
	/* Menu */
	.main-menu {
		position: relative;
		z-index: 9;
		width: auto;
		top: 12px;
		right: 15px;
		float: right;
		@include transition-default;
		color: #484848;
		ul,
		ul li {
			position: relative;
			display: inline-block;
			margin: 0;
			padding: 0;
			a {
				position: relative;
				margin: 0;
				padding: 0;
				display: block;
				padding: 5px 10px;
				white-space: nowrap;
			}
		}
	}
	/*First level styles */
	.main-menu>ul>li span {
		>a {
			color: #484848;
			padding: 0 8px 15px 8px;
			@include fontSize(14px);
			font-weight: 500;
		}
		&:hover>a {
			opacity: 0.7;
		}
	}
	header.sticky .main-menu>ul>li span {
		>a {
			color: #444;
		}
		&:hover>a {
			opacity: 1;
			color: $color-1;
		}
	}
	/* Submenu*/
	.main-menu ul ul {
		position: absolute;
		z-index: 1;
		visibility: hidden;
		left: 3px;
		top: 100%;
		margin: 0;
		display: block;
		padding: 0;
		background: #fff;
		min-width: 200px;
		@include box-shadow (0px 6px 12px 0px rgba(0, 0, 0, 0.175));
		transform: scale(0.4);
		transform-origin: 10% top;
		transition: 0.15s linear, 0.1s opacity cubic-bezier(0.39, 0.575, 0.565, 1), 0.15s transform cubic-bezier(0.1, 1.26, 0.83, 1);
		opacity: 0;
		//@include transition-default (all, 0.2s, ease); // TODO figure out why clean-css is breaking here
		@include border-radius(3px);
		&:before {
			bottom: 100%;
			left: 15%;
			border: solid transparent;
			content: " ";
			height: 0;
			width: 0;
			position: absolute;
			pointer-events: none;
			border-bottom-color: #fff;
			border-width: 7px;
			margin-left: -7px;
		}
		li {
			display: block;
			height: auto;
			padding: 0;
			a {
				@include fontSize(13px);
				color: $body-text-color;
				border-bottom: 1px solid #ededed;
				display: block;
				padding: 15px 10px;
				line-height: $line-height-none;
			}
		}
	}
	.main-menu ul li:hover>ul {
		padding: 0;
		visibility: visible;
		opacity: 1;
		-webkit-transform: scale(1);
		transform: scale(1);
		-webkit-transition-delay: 0.2s;
		transition-delay: 0.2s;
		-webkit-transition-duration: 0s, 0.2s, 0.2s;
		transition-duration: 0s, 0.2s, 0.2s
	}
	.main-menu ul ul li {
		&:first-child a {
			&:hover {
				@include border-radius(3px 3px 0 0);
			}
		}
		&:last-child a {
			border-bottom: none;
			&:hover {
				@include border-radius(0 0 3px 3px);
			}
		}
		&:hover>a {
			background-color: #f9f9f9;
			color: $color-1;
			padding-left: 18px;
		}
	}

}

/* All styles for screen size under 991px
================================================== */
@media only screen and (max-width: 991px) {

	nav#menu {
		display: none !important;
	}
	.mm-menu {
		background: #fff;
	}
	.main-menu {
		top: 0;
		right: 0;
		float: none;
	}
	ul.mm-listview {
		line-height: 25px;
		li {
			a {
				color: $body-text-color!important;
				display: block;
			}
		}
	}

}

```
