### ISSUE TITLE
preserve /* clean-css ignore:... */ comments

### ISSUE THREAD

**Issue by bkarlson** [clean-css/clean-css#1052]
### Environment

* clean-css version: 4.2.1
* node.js version: 10.10
* operating system: OS X 10.14.2

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({

  compatibility: 'ie8',
  format: 'beautify',
  rebase: false,
  level: {
    1: {
      semicolonAfterLastProperty: false,
      selectorsSortingMethod: 'natural'
    },
    2: {
      all: true, 
      mergeSemantically: true, 
      removeUnusedAtRules: false, 
      restructureRules: true
    }
})
```
### Input CSS

```css
/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */

html {
  line-height: 1.15;
  -webkit-text-size-adjust: 100%;
}
[...]
[hidden] {
  display: none;
}
/* clean-css ignore:end */
/*! END normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */```

### Actual output CSS

```css
/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
/* clean-css ignore:start */

html {
  line-height: 1.15;
  -webkit-text-size-adjust: 100%;
}
[...]
[hidden] {
  display: none;
}
```

### Expected output CSS

untouched
------

Basically, because `/* clean-css ignore:... */` are removed on first run, subsequent runs of clean-css messes up the code that is supposed to stay untouched.

Would it make more sense to keep ignore comments as well? I.e. set them to be

```css
/*! clean-css ignore:start */
...
/*! clean-css ignore:end */

```

Cheers!
