### ISSUE TITLE
Improve (-webkit-)?image-set minification

### ISSUE THREAD

**Issue by XhmikosR** [clean-css/clean-css#1064]
https://developer.mozilla.org/en-US/docs/Web/CSS/image-set

Sample:

```css
@media (max-width: 1200px) {
    .logo {
        background-image: url("/images/logo.jpg");
        background-image: -webkit-image-set(
          url("/images/logo@1x.webp") 1x,
          url("/images/logo@2x.webp") 2x
        );
        background-image: image-set(
          url("/images/logo@1x.jpg") 1x,
          url("/images/logo@2x.jpg") 2x
        );
    }
}
```

Currently results in:

```css
@media (max-width:1200px){.logo{background-image:url(/images/logo.jpg);background-image:-webkit-image-set(
          url("/images/logo@1x.webp") 1x,
          url("/images/logo@2x.webp") 2x
        );background-image:image-set(
          url("/images/logo@1x.jpg") 1x,
          url("/images/logo@2x.jpg") 2x
        )}}
```

Quotes could be removed, newlines/whitespace can be reduced too.
