### ISSUE TITLE
Remove duplicate/overridden justify-content rule

### ISSUE THREAD

**Issue by na-oma** [clean-css/clean-css#1068]
### Environment

* clean-css version - `npm ls clean-css`: clean-css@4.2.1 through gulp-clean-css@4.0.0
* node.js version - `node -v`: v10.15.3
* operating system: Windows 10

### Configuration options

```js
cleanCSS({
    level: {
        2: {
            all: true
        }
    }
}
```

### Input CSS

```css
#a {
    justify-content: space-between;
}
#a {
    justify-content: space-around;
}
```

### Actual output CSS

```css
#a {
    justify-content: space-between;
    justify-content: space-around
}
```

### Expected output CSS

```css
#a {
    justify-content: space-around
}
```

### The same happens with just (or any rules in between the two lines)
```css
#asdf {
    justify-content: space-between;
    justify-content: space-around;
}
```

Is this a bug or is this deliberately left out because flexbox is still in the works for https://github.com/jakubpawlowicz/clean-css/milestone/50
