### ISSUE TITLE
font-family & -apple-system

### ISSUE THREAD

**Issue by TigersWay** [clean-css/clean-css#1080]
### Environment
* clean-css: v4.2.1 (via gulp-clean-css)
* node.js: v11.10.0
* OS: Win10 (updated)

Same trouble via https://jakubpawlowicz.github.io/clean-css/
With default configuration.

### Input CSS

```css
.one {
  font-family: -apple-system,BlinkMacSystemFont,"Segoe UI","Roboto","Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
}
.two {
  font-family: apple-system,BlinkMacSystemFont,"Segoe UI","Roboto","Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
}
.one {
  font-family: any;
}
.two {
  font-family: another-any;
}
```

### Actual output CSS

```css
.one{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-family:any}.two{font-family:another-any}
```

### Expected output CSS

```css
.one{font-family:any}.two{font-family:another-any}
```

A lot of frameworks uses "-apple-system" in their default font stack(s). But it does not seem possible to combine font-family properties when that "-apple-system" is involved.

Without the first dash (silly but worth the test) it works.
