### ISSUE TITLE
Merging attributes don't seem to work when the attribute has a dash or value

### ISSUE THREAD

**Issue by squallstar** [clean-css/clean-css#1116]
I am having an issue where rules are not being merged correctly when the HTML attributes contains a dash/minus or have a value.

---

Given the following CSS:

```css
[foo] { color: green}
[foo][bar] { background-color: transparent; color: green }
```

Clean CSS correctly optimises it to

```css
[foo],[foo][bar]{color:green}
[foo][bar]{background-color:transparent}
```

However, if the attributes have a dash in their name or contains a value, it doesn't work as expected. Given the following input:

```css
[data-foo="bar"] { color: green}
[data-foo="bar"][bar-baz="bazbar"] { background-color: transparent; color: green }
```

This is the output:

```css
[data-foo=bar]{color:green}
[data-foo=bar][bar-baz=bazbar]{background-color:transparent;color:green}
```

As you can see, it's not as I would have expected, e.g.:

```css
[data-foo=bar]{color:green}
[data-foo=bar][bar-baz=bazbar]{background-color:transparent;}
```

---

Can you confirm if this is an issue in the library or somehow there's a configuration I can use to make it work for attributes having dashes and or values?

Many thanks.
