### ISSUE TITLE
Duplicated @media rules not being removed

### ISSUE THREAD

**Issue by gagy3798** [clean-css/clean-css#1120]
@media (max-width:767px) {
#header{position:fixed}
.class_a{display:none}
}
@media (max-width:767px) {
#header{position:fixed}
.class_b{background-size:150px}
}

Expected:

@media (max-width:767px) {
#header{position:fixed}
.class_a{display:none}
}
@media (max-width:767px) {
.class_b{background-size:150px}
}

**Comment by 97lunarmare** [comment]
Make sure your optimization level is set to 2 as it is now level 1 by default.

**Comment by vovayatsyuk** [comment]
I have a similar issue with media styles. Duplicates are not removed when the existing properties are found between two media queries.

Tested on https://jakubpawlowicz.github.io/clean-css/.

Here is a file1. Duplicates are not removed:

```css
@media only screen and (max-width:767px) {
    .breadcrumbs {
        padding-left: 15px;
        padding-right: 15px
    }
    .header {
        position: relative;
    }
}
.fieldset {
    padding: 0;
}
@media only screen and (max-width:767px) {
    .breadcrumbs {
        padding-left: 15px;
    }
    .header {
        position: relative;
    }
}
```

Here is a file2. Duplicates are removed:

```css
@media only screen and (max-width:767px) {
    .breadcrumbs {
        padding-left: 15px;
        padding-right: 15px
    }
    .header {
        position: relative;
    }
}
.fieldset {
    margin: 0;
}
@media only screen and (max-width:767px) {
    .breadcrumbs {
        padding-left: 15px;
    }
    .header {
        position: relative;
    }
}
```
