### ISSUE TITLE
clean-css level 2 : drop css variables with important flag, and css variables merged not right

### ISSUE THREAD

**Issue by rhlin** [clean-css/clean-css#1121]
### Environment

* clean-css version - `npm ls clean-css`:  4.2.3
* node.js version - `node -v`: 10.16.3
* operating system: win10

### Configuration options
```js
var CleanCSS = require('clean-css');
new CleanCSS({
  compatibility: 'ie9',
  level: {
     2: {
           skipProperties: ['transition'] 
      }
   },
})
```
This configuration option is default set in Angluar 8.0 CLI builder @angular-devkit/build-angular. 
I run `npx cleancss -O2 a.css --output ./publish/a.min.css` to test the input css using clean-css-cli in fact.

### Input CSS

```css
.case1 {
  border: 1px solid var(--what-ever, red) !important;
}
.case2 {
  border: 1px solid red !important;
  border: 1px solid var(--what-ever, red) !important;
}
.case3 {
  border: 1px solid red;
  border: 1px solid var(--what-ever, red);
}
```

### Actual output CSS

```css
.case1,.case2{border:1px solid!important}.case3{border:1px solid red;border:1px solid var(--what-ever,red)}
```

### Expected output CSS

```css
.case1{border:1px solid var(--what-ever,red)!important}.case2{border:1px solid red!important;border:1px solid var(--what-ever,red)!important}.case3{border:1px solid red;border:1px solid var(--what-ever,red)}
```
--
### Description
 CSS variables(css custom properties) is a Candidate Recommendation Specification. I use it for 
run time properties definition. And Angular 8 Framework use clean-css level 2 as default.
But clean-css level2 **did not recognize css variables**, and drop it with `!important` flag (see case1, case2). case 3 remove important and it is fine
(Level 1 work as fine, but lose those feature like remove duplicate rules etc.)

### Input CSS

```css
.case4{
  background:url('foo.png') no-repeat #fff;
  background:url('foo.png') no-repeat var(--white,#fff);
  background-position: 0 -48px ;
}
```

### Actual output CSS

```css
.case4{background:url(../foo.png) 0 -48px no-repeat #fff;background:url(../foo.png) no-repeat var(--white,#fff)}
```

### Expected output CSS

```css
.case4{background:url(../foo.png) 0 -48px no-repeat #fff;background:url(../foo.png) 0 -48px no-repeat var(--white,#fff)}
```
### Description
case4 shows the second background declarion miss `0 -48px` , and case4 css rule work badly in browser that support css variables.

## **Hope:  a better strategy support css variables.**
suggestion: since css variables can only obtains values in run time, better not process them in compile stage.  and the css properties partially involve css variables should keep the order of declarions, (eg. case4 pisition should not declare before the second background)

Hope add  a better strategy support css variables
