### ISSUE TITLE
Minify border-image via level 2 optimizations

### ISSUE THREAD

**Issue by jakubpawlowicz** [clean-css/clean-css#1138]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - 5.0-pre
* node.js version - 10.19.0
* operating system: NixOS 20.03

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  level: 2
})
```

### Input CSS

```css
.block{border-image: none 100%/1/0 stretch}
```

### Actual output CSS

```css
.block{border-image: none 100%/1/0 stretch}
```

### Expected output CSS

```css
.block{border-image:0}
```

See discussion in #1090 too.
