### ISSUE TITLE
Whitespaces after commas are removed

### ISSUE THREAD

**Issue by zloy2452** [clean-css/clean-css#1155]
### Environment

* gulp-clean-css: v4.2.0
* clean-css version: v5.0.1
* node.js version: v14.15.0
* operating system: Win10 Pro

### Configuration options

```js
function styles() {
	return src('assets/sass/**/*.sass')
		.pipe(sass({ outputStyle: 'expanded' }))
		.pipe(autoprefixer({ cascade: false }))
		.pipe(cleancss({
			level: {
				1: { all: false },
				2: { all: false }
			},
			format: {
				breaks: {
					afterAtRule: 2,
					afterBlockBegins: 1,
					afterBlockEnds: 2,
					afterComment: 1,
					afterProperty: 1,
					afterRuleBegins: 1,
					afterRuleEnds: 2,
					beforeBlockEnds: 1,
					betweenSelectors: 1
				},
				spaces: {
					aroundSelectorRelation: true,
					beforeBlockBegins: true,
					beforeValue: true
				},
				indentBy: 1,
				indentWith: 'tab',
				semicolonAfterLastProperty: true
			}
		}))
		.pipe(dest('assets/css'))
		.pipe(browserSync.stream())
}
```

### Input SASS

```sass
body
	font-family: "Segoe UI", "Helvetica Neue", "Noto Sans", "Liberation Sans", "Apple Color Emoji"
```

### Actual output CSS

```css
body {
	font-family: "Segoe UI","Helvetica Neue","Noto Sans","Liberation Sans","Apple Color Emoji";
}
```

### Expected output CSS

```css
body {
	font-family: "Segoe UI", "Helvetica Neue", "Noto Sans", "Liberation Sans", "Apple Color Emoji";
}
```

I want to keep these whitespaces. Is there any fix for this?
