### ISSUE TITLE
Question: Can I move all media-quires to the bottom?

### ISSUE THREAD

**Issue by puggan** [clean-css/clean-css#1162]
### Environment
clean-css@5.1.2
node v10.19.0
Linux KUMA 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Configuration options
```js
{
    level: {
        2: {
            mergeSemantically: true,
            restructureRules: true,
            selectorsSortingMethod: 'natural',
        }
    }
};
```

### Input CSS
```css
@media (min-width:768px) {
        .col-sm-3 {
                width: 25%
        }
}

.col-xs-6 {
        width: 50%
}
```

### Actual output CSS
```css
'@media (min-width:768px){.col-sm-3{width:25%}}.col-xs-6{width:50%}
```

### Wanted output CSS
```css
'.col-xs-6{width:50%}@media (min-width:768px){.col-sm-3{width:25%}}
```

### Question
If I have concated a few css.file, and then want to make sure that all media-queries are in the bottom,
is there some good way to do it?

A workaround I tested a bit is to concat empty @media-queries to the bottom, and then run CleanCss twice,
first without remove empty, and then with only remove empty on the 2nd run.

Seams to be working, but want to check if there is a better way to solve it?

This test seams to be doing what i want, (even if I don't understand the output middle step).

```js
const CleanCss = require('clean-css');
const uglifyCssOptions2 = {
    level: {
        1: {
            removeEmpty: false,
        },
        2: {
            mergeSemantically: true,
            removeEmpty: false,
            restructureRules: true,
            selectorsSortingMethod: 'natural',
        }
    }
};
const uglifyCssOptions3 = {
    level: {
        1: {
            all: false,
            removeEmpty: true,

        },
        2: {
            all: false,
            removeEmpty: true,
        }
    }
};
const a = '@media (min-width:768px) {\n\t.col-sm-3 {\n\t\twidth: 25%\n\t}\n}\n\n.col-xs-6 {\n\twidth: 50%\n}\n\n@media (min-width:768px) {\n}\n';
console.log('before: ', a);
const cleaner2 = new CleanCss(uglifyCssOptions2);
const a2 = cleaner2.minify(a).styles;
console.log('mid: ', a2);
const cleaner3 = new CleanCss(uglifyCssOptions3);
const a3 = cleaner3.minify(a2).styles;
console.log('after: ', a3);
```
