### ISSUE TITLE
`Arial Black` partially mistaken for color name and converted to hex

### ISSUE THREAD

**Issue by tbentham** [clean-css/clean-css#1163]
I checked if the issue had been raised - last time seems to be #450 in 2015.

I'm actually running [django-tailwind](https://github.com/timonweb/django-tailwind), which in turn runs `cleancss` as part of its CSS building process. Since the CSS below is auto-generated by Tailwind, I don't have direct control over things like quotation marks and comments.

### Environment

* clean-css version: `4.2.3`
* node.js version: `15.9.0`
* operating system: Ubuntu 20.04.2 LTS (GNU/Linux 4.19.128-microsoft-standard x86_64) - running in WSL 2 on Windows 10 64-bit [Version 10.0.19042.985]

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  // default as far as I can tell from django-tailwind settings
})
```

### Input CSS

```css
/* Auto-generated by Tailwind */
.font-impact {
  font-family: Impact, Haettenschweiler, Franklin Gothic Bold, Charcoal, Helvetica Inserat, Bitstream Vera Sans Bold, Arial Black, sans serif;
}
```

### Actual output CSS

```css
.font-impact{font-family:Impact,Haettenschweiler,Franklin Gothic Bold,Charcoal,Helvetica Inserat,Bitstream Vera Sans Bold,Arial #000,sans serif}
```

### Expected output CSS

```css
/* Same as input - no change */
.font-impact {
  font-family: Impact, Haettenschweiler, Franklin Gothic Bold, Charcoal, Helvetica Inserat, Bitstream Vera Sans Bold, Arial Black, sans serif;
}
```
