### ISSUE TITLE
Spaces and line breaks around `var` calls are not removed

### ISSUE THREAD

**Issue by lex111** [clean-css/clean-css#1178]
### Explanation

Hi @jakubpawlowicz, ran into issue that when there are spaces/linebreaks in `var` calls in CSS code, minifier does not remove them. That shouldn't be it, right?

### Precheck
 
* Do a quick search and make sure a bug has not yet been reported; :+1: 
* do a quick check if the bug still exists in the latest patch version; :+1: 
* finally, be nice and have fun! :+1: 

### Environment

* clean-css version - `npm ls clean-css`: 5.3.2
* node.js version - `node -v`: 12.14.0
* operating system: Ubuntu 20.04

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  level: 2,
})
```

### Input CSS

```css
.alert--primary{--ifm-alert-background-color:var(
        --ifm-color-primary-contrast-background
      );--ifm-alert-background-color-highlight:rgba(53, 120, 229, 0.15);--ifm-alert-foreground-color:var(
        --ifm-color-primary-contrast-foreground
      );--ifm-alert-border-color:var(--ifm-color-primary-dark)}
```

### Actual output CSS

```css
.alert--primary{--ifm-alert-background-color:var(
        --ifm-color-primary-contrast-background
      );--ifm-alert-background-color-highlight:rgba(53, 120, 229, 0.15);--ifm-alert-foreground-color:var(
        --ifm-color-primary-contrast-foreground
      );--ifm-alert-border-color:var(--ifm-color-primary-dark)}
```

### Expected output CSS

```css
.alert--primary{--ifm-alert-background-color:var(--ifm-color-primary-contrast-background);--ifm-alert-background-color-highlight:rgba(53, 120, 229, 0.15);--ifm-alert-foreground-color:var(--ifm-color-primary-contrast-foreground);--ifm-alert-border-color:var(--ifm-color-primary-dark)}
```

![image](https://user-images.githubusercontent.com/4408379/127927878-efb2a29d-53db-4acf-9329-bb98c237c260.png)
