### ISSUE TITLE
CSS variables containing only whitespace are incorrectly removed

### ISSUE THREAD

**Issue by adamwathan** [clean-css/clean-css#1180]
### Environment

Just testing at https://clean-css.github.io/

### Input CSS

```css
.inset {
  --inset: inset;
}

.outset {
  --inset: ;
}

.shadow {
  box-shadow: var(--inset) 0 2px 2px #0004;
}
```

### Actual output CSS

```css
.inset{--inset:inset}.shadow{box-shadow:var(--inset) 0 2px 2px #0004}
```

### Expected output CSS

```css
.inset{--inset:inset}.outset{--inset: ;}.shadow{box-shadow:var(--inset) 0 2px 2px #0004}
```

### Explanation

Whitespace is a valid value for a CSS variable, like this:

```css
--my-var: ;
```

This is semantically _not_ the same as:

```css
--my-var:;
```

From [CSS Custom Properties for Cascading Variables Module Level 1](https://www.w3.org/TR/css-variables-1/#syntax):

> Note: While <declaration-value> must represent at least one token, that one token may be whitespace. This implies that --foo: ; is valid, and the corresponding var(--foo) call would have a single space as its substitution value, but --foo:; is invalid.

Because of this issue, clean-css currently cannot be used with Tailwind CSS, as we rely on this feature a lot to support class composition in the framework.

Thanks for your awesome work on this lib ❤️
