### ISSUE TITLE
Optimizing properties of level 2 removes hsl values

### ISSUE THREAD

**Issue by Vatoth** [clean-css/clean-css#1181]
### Precheck
 
Using 2 level, color values specified in hsl format are removed.

Similar to https://github.com/clean-css/clean-css/issues/1156

### Environment

* clean-css version - `5.1.5`
* node.js version - `14.17.5`
* operating system - `Linux 5.13.12`

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({ inline: false, level: 2 })
```

### Input CSS

```css
.zone.contacts .size_1_3 > a {
      border: 3px solid hsl(0deg 0 85%);
}
```

### Actual output CSS

```css
.zone.contacts .size_1_3>a{border:3px solid}
```

### Expected output CSS

```css
.zone.contacts .size_1_3>a{border:3px solid hsl(0deg 0 85%)}
```

**Comment by Vatoth** [comment]
Hello @jakubpawlowicz Yeah nice catch !
I'm trying the lib without the `deg` and with `hsl(0 0 85%)` but it doesn't appear to work.

**Comment by jakubpawlowicz** [comment]
It's fixed on main branch, due in 5.3 today.

**Comment by boris-petrov** [comment]
@jakubpawlowicz - are you sure that's fixed? Using 5.3.0 and the same example as in the original post I get the same result as him - `hsl` is removed. Adding commas also doesn't help.

**Comment by jakubpawlowicz** [comment]
@boris-petrov 5.3.0 is the version used on https://clean-css.github.io/ - there it works just fine with the original bug report example. Is your case any different? Could be an edge case.

**Comment by boris-petrov** [comment]
@jakubpawlowicz - you can also reproduce the issue there - but be sure to enable `level 2 optimizations` (which aren't on by default).

**Comment by jakubpawlowicz** [comment]
My bad, you are right. Will look into it.

**Comment by jakubpawlowicz** [comment]
It turned out clean-css.github.io didn't have 5.3.0 deployed. Now it works there. Tests also pass fine so it could be an edge case.

**Comment by boris-petrov** [comment]
@jakubpawlowicz not sure if the problem is on my side but I still get the same result on https://clean-css.github.io/ . Also, it still says it's using version 5.1.3, perhaps some caching issue? I did try with multiple browsers though.

I also tried `clean-css-cli` - installed version 5.6.0 (not sure which `clean-css` it uses underneath) but it gives the same result. Trying with the example on the original post:

`foo.css`:
```css
.zone.contacts .size_1_3 > a {
      border: 3px solid hsl(0deg 0 85%);
}
```

```
% cleancss -O2 foo.css
.zone.contacts .size_1_3>a{border:3px solid}
```

**Comment by jakubpawlowicz** [comment]
I see what's the problem: consider "hsl(0deg 0 85%)" vs "hsl(0deg 0% 85%)". Is hsl color supposed to work when second value is not given a percentage? Could it be fine only when the value is zero?

**Comment by boris-petrov** [comment]
Not sure about that, probably it is OK to not use percentage as in most places CSS accepts also numbers without a unit.

Also, here are more examples that are removed:

```css
.foo {
  border-top: 0.063rem solid hsl(210deg, 10%, 24%);
}

.foo {
  border-top: 0.063rem solid hsl(210deg, 10.8108108108%, 24.649859944%);
}
```
