### ISSUE TITLE
Issue with tailwindcss

### ISSUE THREAD

**Issue by yellow1912** [clean-css/clean-css#1185]
### Environment

* clean-css version - `npm ls clean-css`: 5.2.0
* node.js version - `node -v`: v14.17.0
* operating system: Ubuntu 20

### Configuration options
CLI:
```
cleancss -O2 --format minify
```

### Input CSS

```css
.test {--tw-blur: var(--tw-empty,/*!*/ /*!*/);}
```

### Actual output CSS

```css
.test{--tw-blur: var(--tw-empty,);/*!*//*!*/}
```

### Expected output CSS

```css
.test {--tw-blur: var(--tw-empty,/*!*/ /*!*/);}
```

I thought the latest PR should have fixed it but it seems to have the same issue.
