### ISSUE TITLE
Option level1 replaceZeroUnits: false not working

### ISSUE THREAD

**Issue by macakronos** [clean-css/clean-css#1197]
Hello first, I hope you are well.

In level 1 optimization configurations, the `replaceZeroUnits` option is not disabled. I understand from the description, that it removes the units when the value is 0. I have set it to `false`, but it removes the units.

I have tried the online tool, and have disabled all level 1 subrules, but still get the same result. Only if I completely disable level 1 does it work, of course it's not what I want.

### Environment

* clean-css: `5.2.3`,
* node.js version - `v14.17.1`:
* operating system: `MacOS 11.3`

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
 level: {
      1:{
         all: true,
         replaceZeroUnits: false
      },
      2:{}
    }
})
```

### Input CSS

```css
.fs-px {
    font-size: calc(4.28571vw + 18.28571px);
    min-width: 0vw;
}
```

### Actual output CSS

```css
.fs-px {
    font-size: calc(4.28571vw + 18.28571px);
    min-width: 0;
}
```

### Expected output CSS

```css
.fs-px {
    font-size: calc(4.28571vw + 18.28571px);
    min-width: 0vw;
}
```
