### ISSUE TITLE
Broken url path in font-face

### ISSUE THREAD

**Issue by Lukkian** [clean-css/clean-css#1200]
### Environment

* jsDelivr using clean-css v5.2.2

### Input CSS [bootstrap-icons.css](https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css)

```css
@font-face {
  font-family: "bootstrap-icons";
  src: url("./fonts/bootstrap-icons.woff2?e2f6e48459d8b0f394eea57aba940179") format("woff2"),
url("./fonts/bootstrap-icons.woff?e2f6e48459d8b0f394eea57aba940179") format("woff");
}
```

### Actual output CSS [bootstrap-icons.min.css](https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.min.css)

```css
@font-face{font-family:bootstrap-icons;src:url("../fonts/bootstrap-icons.woff2?e2f6e48459d8b0f394eea57aba940179") format("woff2"),url("../fonts/bootstrap-icons.woff?e2f6e48459d8b0f394eea57aba940179") format("woff")}
```

### Expected output CSS

```css
@font-face{font-family:bootstrap-icons;src:url("./fonts/bootstrap-icons.woff2?e2f6e48459d8b0f394eea57aba940179") format("woff2"),url("./fonts/bootstrap-icons.woff?e2f6e48459d8b0f394eea57aba940179") format("woff")}
```
This causes a 404 error in the .woff and woff2 font files.
This behavior does not occur in [clean-css v4.2.4](https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.min.css).
