### ISSUE TITLE
Cannot read property '0' of undefined in level-2/properties/populate-components.js using font:

### ISSUE THREAD

**Issue by mostafa-hisham** [clean-css/clean-css#1206]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - `npm ls clean-css`: 5.2.4
* node.js version - `node -v`: 14.19.0 and v17.6.0
* operating system: linux

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS(
 {
                level: {
                    1: {
                        specialComments: 0,
                    },
                    2: {
                        removeUnusedAtRules: true,
                    }
                },
                inline: ['local', 'remote'],
})
```

### Input CSS

```css
    <style>
        @font-face {
            font-family: "Font Awesome 5 Pro";
            font-display: swap;
            font-style: normal;
            font-weight: 300;
            src: url(https://rocketlabsqa.ovh/wp-content/themes/rehub-theme/admin/fonts/fontawesome/webfonts/fa-light-300.eot);
            src: url(https://rocketlabsqa.ovh/wp-content/themes/rehub-theme/admin/fonts/fontawesome/webfonts/fa-light-300.eot?#iefix) format("embedded-opentype"),
            url(https://rocketlabsqa.ovh/wp-content/themes/rehub-theme/admin/fonts/fontawesome/webfonts/fa-light-300.woff2) format("woff2"),
            url(https://rocketlabsqa.ovh/wp-content/themes/rehub-theme/admin/fonts/fontawesome/webfonts/fa-light-300.woff) format("woff"),
            url(https://rocketlabsqa.ovh/wp-content/themes/rehub-theme/admin/fonts/fontawesome/webfonts/fa-light-300.ttf) format("truetype"),
            url(https://rocketlabsqa.ovh/wp-content/themes/rehub-theme/admin/fonts/fontawesome/webfonts/fa-light-300.svg#fontawesome) format("svg")
        }
        .example {
            font: 14px Font Awesome\ 5 Pro;
        }
    </style>
```

### Actual output CSS

```/home/mostafa/zDevEnv/wp-media/nodejs-treeshaker/node_modules/clean-css/lib/optimizer/level-2/properties/populate-components.js:38
          throw e;
          ^

TypeError: Cannot read property '0' of undefined
    at Object.font [as breakUp] (/home/mostafa/zDevEnv/wp-media/nodejs-treeshaker/node_modules/clean-css/lib/optimizer/configuration/break-up.js:302:91)
    at populateComponents (/home/mostafa/zDevEnv/wp-media/nodejs-treeshaker/node_modules/clean-css/lib/optimizer/level-2/properties/populate-components.js:22:42)
    at /home/mostafa/zDevEnv/wp-media/nodejs-treeshaker/node_modules/clean-css/lib/optimizer/level-2/remove-unused-at-rules.js:141:9
    at markUsedAtRules (/home/mostafa/zDevEnv/wp-media/nodejs-treeshaker/node_modules/clean-css/lib/optimizer/level-2/remove-unused-at-rules.js:63:9)
    at removeUnusedAtRule (/home/mostafa/zDevEnv/wp-media/nodejs-treeshaker/node_modules/clean-css/lib/optimizer/level-2/remove-unused-at-rules.js:43:3)
    at removeUnusedAtRules (/home/mostafa/zDevEnv/wp-media/nodejs-treeshaker/node_modules/clean-css/lib/optimizer/level-2/remove-unused-at-rules.js:22:3)
    at level2Optimize (/home/mostafa/zDevEnv/wp-media/nodejs-treeshaker/node_modules/clean-css/lib/optimizer/level-2/optimize.js:118:5)
    at optimize (/home/mostafa/zDevEnv/wp-media/nodejs-treeshaker/node_modules/clean-css/lib/clean.js:221:5)
    at /home/mostafa/zDevEnv/wp-media/nodejs-treeshaker/node_modules/clean-css/lib/clean.js:195:29
    at /home/mostafa/zDevEnv/wp-media/nodejs-treeshaker/node_modules/clean-css/lib/reader/read-sources.js:26:64

```

### Expected output CSS
```
        @font-face {
            font-family: "Font Awesome 5 Pro";
            font-display: swap;
            font-style: normal;
            font-weight: 300;
            src: url(https://rocketlabsqa.ovh/wp-content/themes/rehub-theme/admin/fonts/fontawesome/webfonts/fa-light-300.eot);
            src: url(https://rocketlabsqa.ovh/wp-content/themes/rehub-theme/admin/fonts/fontawesome/webfonts/fa-light-300.eot?#iefix) format("embedded-opentype"),
            url(https://rocketlabsqa.ovh/wp-content/themes/rehub-theme/admin/fonts/fontawesome/webfonts/fa-light-300.woff2) format("woff2"),
            url(https://rocketlabsqa.ovh/wp-content/themes/rehub-theme/admin/fonts/fontawesome/webfonts/fa-light-300.woff) format("woff"),
            url(https://rocketlabsqa.ovh/wp-content/themes/rehub-theme/admin/fonts/fontawesome/webfonts/fa-light-300.ttf) format("truetype"),
            url(https://rocketlabsqa.ovh/wp-content/themes/rehub-theme/admin/fonts/fontawesome/webfonts/fa-light-300.svg#fontawesome) format("svg")
        }
        .example {
            font: 14px Font Awesome\ 5 Pro;
        }
```
### Comment
In this case 
the font family is actually used and should e returned 
i think there is a problem with using the font family name like this `Font Awesome\ 5 Pro`
also `property.all` is not defined
