### ISSUE TITLE
bug : media prefers-reduced-motion not correctly parsed

### ISSUE THREAD

**Issue by abarre** [clean-css/clean-css#1207]
### Environment

* clean-css version - `5.1.3`:
* node.js version - `14`:
* operating system: linux

### Configuration options

![Capture d’écran 2022-03-17 à 12 38 32](https://user-images.githubusercontent.com/928701/158800868-82bf13be-eb7c-48f1-9a77-1249b1bf1324.png)
![Capture d’écran 2022-03-17 à 12 38 42](https://user-images.githubusercontent.com/928701/158800874-ed241687-2d6d-46b8-a33d-78dcac8df6cb.png)
![Capture d’écran 2022-03-17 à 12 39 49](https://user-images.githubusercontent.com/928701/158801015-f3ef0098-835e-4dff-9b23-5876a1948590.png)

this bugs seems related to : 
- remove empty rules and nested blocks (after level 1 optimizations)
- tidy selectors

### Input CSS

```css
@​media (prefers-reduced-motion:reduce) {
  * {
    transition: none !important;
  }
}
script {
  display: none !important;
}
em {
  font-style: normal;
}
```

### Actual output CSS

```css
em{font-style:normal}
```

### Expected output CSS

```css
@​media (prefers-reduced-motion:reduce) {* {transition: none !important;}}script {display: none !important;}em {font-style: normal;}
```

**Comment by jakubpawlowicz** [comment]
@abarre - after a moment I noticed that my CSS editor wasn't highlighting the code properly, so using elimination I figured out that your CSS snippet has a character between initial `@` and `m` in media. Check my CSS snippet and it'll work fine.

```css
@media (prefers-reduced-motion:reduce) {
  * {
    transition: none !important;
  }
}
script {
  display: none !important;
}
em {
  font-style: normal;
}
```

A hex editor yields there's a three-byte character `E2808B` there.

I don't think clean-css should deal with it in any way, but please correct me if I'm wrong.
