### ISSUE TITLE
Correct handling of <family-name> in font-family

### ISSUE THREAD

**Issue by yisibl** [clean-css/clean-css#1208]
## Input

```css
.foo {
  font-family: 'sans-serif', 'default';
}
```

## Output

```css
.foo{font-family:sans-serif,default}
```

![image](https://user-images.githubusercontent.com/2784308/159432123-2a1d73f7-0855-454f-b183-d97039b0a6b2.png)

## Expected

```css
.foo{font-family:'sans-serif','default'}
```

See also: https://github.com/parcel-bundler/parcel-css/issues/120
