### ISSUE TITLE
removeUnusedAtRules removes @font-face for fonts used in CSS variable declarations

### ISSUE THREAD

**Issue by alecglassford** [clean-css/clean-css#1229]
### Environment

* clean-css version - 5.3.1
* node.js version - `node -v`: 16.16.0
* operating system: N/A

### Configuration options

```js
new CleanCSS({ level: { 2: { removeUnusedAtRules: true } } })
```

### Input CSS

```css
@font-face {
    font-family: test;
    src: url(https://test);
}

:root {
    --serif-stack: test;
}

p {
    font-family: var(--serif-stack);
}
```

### Actual output CSS

```css
:root{--serif-stack:test}p{font-family:var(--serif-stack)}
```

### Expected output CSS

```css
@font-face{font-family:test;src:url(https://test)}:root{--serif-stack:test}p{font-family:var(--serif-stack)}
```

---

In this example, it seems that because the `test` font is only used in a CSS variable declaration, clean-css mistakenly considers it "unused."
