### ISSUE TITLE
Support @layer keyword

### ISSUE THREAD

**Issue by earlAchromatic** [clean-css/clean-css#1242]
### Environment

* clean-css version: 5.3.1
* node.js version: 16
* operating system: MacOS

### Configuration options

using grunt-contrib-cssmin (no config)

### Input CSS

```css
@layer customlayername {
    .custom-rule {
        background: red;
    }
}
```

### Actual output CSS

```css
@layer customlayername {
        background: red;
}
```

And error: 

```js
Unexpected '}' at .tmp/css/app.css.,Unexpected '}'
```
