### ISSUE TITLE
"mergeNonAdjacentRules" not works in some cases

### ISSUE THREAD

**Issue by GoodDayForSurf** [clean-css/clean-css#1244]
### Environment

* clean-css version - 5.3.2
* node.js version - v18.12.1
* operating system: Win

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({"level": {2: { mergeNonAdjacentRules: true } } })
```

### Input CSS

```css
.selector .title {
  border: 0;
}
.wrapper .container {
  padding: 0;
}
.other{
   border-radius: 1px;
}
.selector .title {
  padding: 1px;
}
```

### Actual output CSS

```css
.selector .title {
  border: 0;
}
.wrapper .container {
  padding: 0;
}
.other{
  border-radius: 1px;
}
.selector .title {
  padding: 1px;
}
```

### Expected output CSS

```css
.wrapper .container {
  padding: 0;
}
.other{
  border-radius: 1px;
}
.selector .title {
  border: 0;
  padding: 1px;
}
```

If you replace **border-radius** with any other property, the merge will work as expected.
