### ISSUE TITLE
Spaces removed from :is statement

### ISSUE THREAD

**Issue by 04alband** [clean-css/clean-css#1246]
Hi, this seems very similar to this closed issue: https://github.com/clean-css/clean-css/issues/996

I'm using the latest gulp-clean-css (4.3.0) which I believe is a wrapper for clean-css.
I'm seeing spaces be removed from a complex :is() statement, changing the meaning of it. I've tried disabling `spaces.aroundSelectorRelation` but that didn't seem to help. The only thing I've found that solves it is changing optimisation to level 0, but that removes a lot of other nice stuff. See example...

### Environment

* clean-css version - `npm ls clean-css`: gulp-clean-css is 4.3.0
* node.js version - `node -v`: v16.14.2
* operating system: Windows

### Configuration options

My gulp task is very simple, like this:

```js
gulp.task('build:sass', () => {
    console.log('building sass');

    return gulp.src(paths.sass.src, { since: gulp.lastRun('build:sass') })
        .pipe(sourcemaps.init())
        .pipe(sass().on('error', sass.logError))
        .pipe(cleanCSS(cleanOptions))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest(paths.sass.dest));
});
```

For the options, I've tried playing with many options but the default no-options produces the error.

### Input CSS

```css
:is(.dataTables_wrapper > .dataTables_scroll .dataTables_scrollHead table.dataTable, .dataTables_wrapper > table.dataTable) thead {
	background: red;
}
```

### Actual output CSS

```css
:is(.dataTables_wrapper>.dataTables_scroll.dataTables_scrollHeadtable.dataTable,.dataTables_wrapper>table.dataTable) thead {
  background: red
}
```

### Expected output CSS

```css
:is(.dataTables_wrapper > .dataTables_scroll .dataTables_scrollHead table.dataTable, .dataTables_wrapper > table.dataTable) thead {
	background: red;
}
```

If I'm doing something wrong, I'm sorry and any help would be greatly appreciated.

**Comment by shuffgy** [comment]
@04alband i had the same issue but did not want to set all rules to false.
Also for me it was not `removeWhitespace: false` that fixed it, it was `tidySelectors: false`

Input:
```scss
&:nth-last-child(1 of .event__info) {
	margin-bottom: var(--margin-l);
}
```

Here was the output `:nth-last-child(1of.event__info) {` before, now its correct.
