### ISSUE TITLE
clean css cli do not round font-size(px)  line-height

### ISSUE THREAD

**Issue by kaiceo** [clean-css/clean-css#1249]
### Configuration options
 cleancss -O1 roundingPrecision:*=2,px=0  test/font.css -o t1.css

### Input CSS

```css
.fse8{
    font-size:1.151643px;
    line-height:0.932129;   
}
.m16b{transform:matrix(0.260929,0.000000,0.000000,0.250000,0,0);-ms-transform:matrix(0.260929,0.000000,0.000000,0.250000,0,0);-webkit-transform:matrix(0.260929,0.000000,0.000000,0.250000,0,0);}
._249{margin-left:-1578.200939px;}
.y5a46{bottom:125.267522px;}
.x155{left:481.734256px;}
.v0{vertical-align:0.000000px;}
.ls0{letter-spacing:0.000000px;}
.ws0{word-spacing:0.000000px;}
```

### Actual output CSS

```
.fse8{font-size:1.151643px;line-height:.932129}
.m16b{transform:matrix(.260929,0,0,.25,0,0);
-ms-transform:matrix(.260929,0,0,.25,0,0);
-webkit-transform:matrix(.260929,0,0,.25,0,0)}
._249{margin-left:-1578px}.y5a46{bottom:125px}
.x155{left:482px}
.v0{vertical-align:0}
.ls0{letter-spacing:0}
.ws0{word-spacing:0.000000px}
```

### Expected output CSS

```
.fse8{font-size:1.15px;line-height:.93}
.m16b{transform:matrix(.26,0,0,.25,0,0);
-ms-transform:matrix(.26,0,0,.25,0,0);
-webkit-transform:matrix(.26,0,0,.25,0,0)}
._249{margin-left:-1578px}.y5a46{bottom:125px}
.x155{left:482px}a
.v0{vertical-align:0}
.ls0{letter-spacing:0}
.ws0{word-spacing:0}
```
not round font-size   line-height  martrix  word-sapcing
