### ISSUE TITLE
clean-css doesn't separate all spaces in the selector, instead it combines them all.

### ISSUE THREAD

**Issue by elhakimyasya** [clean-css/clean-css#1250]
Doesn't separate all spaces in the selector, instead it combines them all.

### Configuration options

```js
new CleanCSS({
    level: {
        1: {
            specialComments: 0
        }
    }
})
```

### Input CSS

```css
:is([dir=ltr] .xxx #xxxx a svg) {
    margin-right: .75rem
}
```

### Actual output CSS

```css
:is([dir=ltr].xxx#xxxxasvg){margin-right:.75rem}
```

### Expected output CSS

```css
:is([dir=ltr] .xxx #xxxx a svg){margin-right:.75rem}
```
