### ISSUE TITLE
Parsing error on `content: "\<";` in CSS

### ISSUE THREAD

**Issue by coaxial** [clean-css/clean-css#1253]
__IMPORTANT: clean-css is now in a [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209). PRs are still welcome, and I will try do an occasional bugfix relase.__

### Precheck

* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - `npm ls clean-css`: `clean-css@5.3.2`
* node.js version - `node -v`: 16.20.0
* operating system: Mint 20.3

### Configuration options

Used through html-minifier-terser

### Input CSS

```css
.fa-less-than::before {
  content: "\<";
}
```

### Actual output CSS

No output, but an error:
```
Minification error on _site/assets/css/hello.css
Parse Error: <";
}
```

### Expected output CSS

```css
.fa-less-than::before{content:"\<";}  // I think?
```
