### ISSUE TITLE
v5.3.2, still stripping away @container queries

### ISSUE THREAD

**Issue by osahan** [clean-css/clean-css#1260]
### Environment

* clean-css version - `5.3.2`:
* node.js version - `20.7.0`:
* operating system: Mac OS Sonoma 14.0

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS()
```

### Input CSS

```css
.container {
    container-type: inline-size;
}
.card {
    background-color: blue;
}
@container (min-width: 500px) {
    .card {
        background-color: yellow;
    }
}
```

### Actual output CSS

```css
.container{container-type:inline-size}.card{background-color:#00f}
```

### Expected output CSS

```css
.container{container-type:inline-size}.card{background-color:#00f}@container(min-width: 500px){.card{background-color:#ff0}
```
