### ISSUE TITLE
@import statement are automatically inserted "url()"

### ISSUE THREAD

**Issue by WangZhenHao** [clean-css/clean-css#1268]
### Environment

* clean-css version - `^5.3.3`:
* node.js version - `v18.18.2`:
* operating system: win 10

### Configuration options

```js
const css = "@import '../commont.wxss'; .test{ font-size: 12px; }"

console.log(new CleanCSS({inline: false }).minify(css))
```

### Actual output CSS

```css
@import url(../commont.wxss);.test{font-size:12px}
```

### Expected output CSS

```css
@import '../commont.wxss';.test{font-size:12px}
```

### Desc
I'm only just want to minify my CSS code, but clean-css will automatically inserted "url()" keywork for my code.

I'm use option `inline: false`, but It don't work! How can I resolve this problem? Thanks!
