### ISSUE TITLE
How to remove whitespaces after commas on v5？

### ISSUE THREAD

**Issue by zhixiaotong** [clean-css/clean-css#1269]
__IMPORTANT: clean-css is now in a [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209). PRs are still welcome, and I will try do an occasional bugfix relase.__

### Precheck

* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - `npm ls clean-css`:
* node.js version - `node -v`:
* operating system:

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  compatibility: '*'
})
```

### Input CSS

```css
.a{
   transition: cubic-bezier(.55, 0, .1, 1) opacity var(--el-transition-duration);
}
```

### Actual output CSS

```css
.a{transition:cubic-bezier(.55, 0, .1, 1) opacity var(--el-transition-duration)}
```

### Expected output CSS

```css
.a{transition:cubic-bezier(.55,0,.1,1) opacity var(--el-transition-duration)}
```
![image](https://github.com/clean-css/clean-css/assets/34681550/63e6d99e-24e2-457b-a0ba-93b3a81589da)

I tried on the official website and failed.
