### ISSUE TITLE
Level 1 optimization `replaceZeroUnits:false` is ignored

### ISSUE THREAD

**Issue by mrebillard-lmwr** [clean-css/clean-css#1278]
### Environment

* clean-css version - `5.3.3`:
* node.js version - `14.21.3`:
* operating system: macOS 13

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  inline: [ 'local' ],
  level: { 1: { replaceZeroUnits: false } },
  returnPromise: true
})
```

### Input CSS

```css
.test {
    transform: translateX(calc((-100% * 2) + var(--slide-content-translate-x, 0%)));
}
```

### Actual output CSS

```css
.test{transform:translateX(calc((-100% * 2) + var(--slide-content-translate-x,0)))}
```

### Expected output CSS

```css
.test{transform:translateX(calc((-100% * 2) + var(--slide-content-translate-x,0%)))}
```

I try to keep units on 0 value setting Level 1 option `replaceZeroUnits` to false, but unit is removed.
Setting the level to 0, the unit is preserved.
The unit in that case is required as CSS var fallback.
Thanks :)
