### ISSUE TITLE
Selector ':nth-last-child(1 of selector) ' breaks 

### ISSUE THREAD

**Issue by miherlosev** [clean-css/clean-css#1280]
Example to reproduce:
```
var CleanCSS = require('clean-css');
const fs = require('fs');

var input = '.dxbl-pivot > table > thead > tr.dxbl-pivot-area-row > th:nth-last-child(1 of .dxbl-pivot-area-row-field) {' + 
'  border-right-width: var(--dxbl-pivot-border-width);' +
'}';
var options = { /* options */ };
var output = new CleanCSS(options).minify(input);

fs.writeFileSync('output.css', output.styles);
```

The output is
```css
.dxbl-pivot>table>thead>tr.dxbl-pivot-area-row>th:nth-last-child(1of.dxbl-pivot-area-row-field){border-right-width:var(--dxbl-pivot-border-width)}
```

Correct output
```css
.dxbl-pivot>table>thead>tr.dxbl-pivot-area-row>th:nth-last-child(1 of.dxbl-pivot-area-row-field){border-right-width:var(--dxbl-pivot-border-width)}
```

**Comment by robyngraf** [comment]
I've run into this issue too.
`:nth-child(1 of button)`
becomes
`:nth-child(1ofbutton)`

**Comment by robyngraf** [comment]
As a workaround, this issue can be patched up in a website with something like this:
```
const style = document.getElementsByTagName('style')[0];
style.innerHTML = style.innerHTML.replaceAll('ofbutton', ' of button');
```

**Comment by MonkeyDo** [comment]
Interestingly, when I have a `:not` pseudo-selector before the same rule, it seems to keep the space between '1' and 'of':
Tested on the clean-css website with latest version (5.1.3) and default settings:
Input:
```less
div:nth-child(1 of .fnord) {
    color:black;
}
div:not(:nth-child(1 of .fnord)) {
    color:red;
}
``` 

Output:
```css
div:nth-child(1of.fnord){color:#000}div:not(:nth-child(1 of .fnord)){color:red}
```
Note the second `:nth-child(1 of .fnord)` has the expected space
