### ISSUE TITLE
keepSpecialComments edge-case

### ISSUE THREAD

**Issue by Mottie** [clean-css/clean-css#369]
I am trying to minify a style that is to be used on userstyles.org. So the css has placeholder comments that will be replaced with user selected styling. Everything works for the most part except when a comment is set for a background. The example below will explain it better:

Starting with this css snippet (the `!` in the comment was added for testing; [userstyles placeholders](https://userstyles.org/help/coding#help-style-settings-placeholders) actually look like this: `/*[[base-color]]*/`

``` css
div {
  color: /*![[base-color]]*/ !important;
}
a {
  background: /*![[base-color]]*/ !important;
}
::selection {
  background-color: /*![[base-color]]*/ !important;
  color: #fff !important;
}
::-moz-selection {
  background: /*![[base-color]]*/ !important;
  color: #fff !important;
}
```

When minified, the result appears like this (carriage returns added to make it readable)

``` css
div{color:/*![[base-color]]*/!important}
a{background:0 0!important}
::selection{background-color:/*![[base-color]]*/!important;color:#fff!important}
::-moz-selection{background:0 0!important;color:#fff!important}
```

When `background: /*![[base-color]]*/ !important;` is encountered, it is replaced by `background:0 0!important`

When `background-color: /*![[base-color]]*/ !important;` is encountered, it is correctly replaced and minified into `background-color:/*![[base-color]]*/!important;`.

I know this is an edge-case, but I thought I'd report it anyway.
