### ISSUE TITLE
clean-css removes wildcard selector

### ISSUE THREAD

**Issue by PalleZingmark** [clean-css/clean-css#444]
I'm using clean-css v3.0.7, and it seems like _clean-css_ removes the wildcard selectors.

Before:

``` CSS
*,
*:before,
*:after {
    box-sizing: border-box;
}
```

After:

``` CSS
:before,:after{box-sizing:border-box}
```

Expected:

``` CSS
*,*:before,*:after{box-sizing:border-box}
```

I've tested all kinds of different arguments, but nothing seems to fix this.
Any ideas?

**Comment by jakubpawlowicz** [comment]
I've just run it locally on 3.0.7 as well and here's the output:

```shell
echo '*, *:after, *:before { box-sizing: border-box; }' | cleancss
*,:after,:before{box-sizing:border-box}
```

`:after` seems to works equally well to `*:after` in latest Firefox and Chrome, however I haven't checked in other browsers.

**Comment by PalleZingmark** [comment]
That is strange, that doesn't work for me either.
Tried it out on another computer, same problem there. (see attachment)
![image](https://cloud.githubusercontent.com/assets/367036/5862749/8489e276-a274-11e4-8a90-ce40591a0e9a.png)

**Comment by jakubpawlowicz** [comment]
Does it mean `*:after` and `:after` mean something different? Otherwise it should be OK.

**Comment by PalleZingmark** [comment]
If I'm interpreting the W3C's recommendation correctly, it should be ok to omit the asterix.

W3C recommendation:
> If a universal selector represented by * (i.e. without a namespace prefix) is not the only 
> component of a sequence of simple selectors selectors or is immediately followed 
> by a pseudo-element, then the * may be omitted and the universal selector's presence implied

..but they also say: 
> Note: it is recommended that the * not be omitted, because it decreases the 
> potential confusion between, for example, div :first-child and div:first-child. 
> Here, div *:first-child is more readable.

**Comment by jakubpawlowicz** [comment]
Hmmm, I think quite the opposite.

(...) is not the only component of a sequence of simple selectors (e.g. `div > * > span`) or is immediately followed by a pseudo-element (e.g. `*:after`) then the * **may** be omitted (...)

**Comment by jakubpawlowicz** [comment]
I'm closing it for now, please reopen if clean-css breaks universal selectors in any way.

**Comment by sbrink** [comment]
This issue is still relevant. It breaks Bootrap 4 beta. (clean-css version 4.0.13)

Boostrap uses it in the new beta version 4:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss#L21

The result are broken .row classes for example.
Instead of a width of 1140px, you get a width of 1170px.

**Comment by jakubpawlowicz** [comment]
So let's reopen it. Any details in which browsers it breaks styling?

**Comment by sbrink** [comment]
I've tested:

* Chrome 60.0.3112.90 (Official Build) (64-bit) (Mac)
* Firefox 54.0.1 (64-bit) (Mac)

**Comment by jakubpawlowicz** [comment]
👍 I wonder if it's related to removing the asterisk from before pseudo classes and pseudo elements, i.e. `*:before` or `*::before`. Need to investigate.

Btw, is Bootstrap 4 clean-css dependency locked at 4.0.13 or would you consider upgrading to 4.1?

**Comment by sbrink** [comment]
It's related to the *

I fixed it temporarily with the following additional selector:

```css
* {
  box-sizing: border-box;
}
```

I upgraded to 4.1.7. It' makes no difference. The complete removal of * seems to be the problem.

**before:**

```css
*,
*::before,
*::after {
  box-sizing: border-box; // 1
}
```

**after:**

```css
:before,:after{box-sizing:border-box}
```

So the * is missing. Right should be:


```css
*,:before,:after{box-sizing:border-box}
```
