### ISSUE TITLE
Some properties aren't getting merged into a single selector

### ISSUE THREAD

**Issue by markmiro** [clean-css/clean-css#623]
``` css
.a {
  display: -webkit-flex;
  display: flex;
}
.b {
  display: -webkit-flex;
  display: flex;
  opacity: red;
}
```

Becomes:

``` css
.a,.b{display:-webkit-flex}.a{display:flex}.b{display:flex;opacity:red}
```

Expected:

``` css
.a,.b{display:-webkit-flex;display:flex}.b{opacity:red}
```
