### ISSUE TITLE
Improve media merging

### ISSUE THREAD

**Issue by jakubpawlowicz** [clean-css/clean-css#687]
See https://github.com/jakubpawlowicz/clean-css/issues/607#issuecomment-145650346 /cc @ajmueller 

``` css
@media only screen and (min-width: 60em) {
    table th {
        font-size: 18px;
        font-size: 1.125rem;
    }
}
table td {
    background-color: white;
    border: none;
    font-size: 14px;
    font-size: 0.875rem;
}
@media only screen and (min-width: 60em) {
    table td {
        font-size: 16px;
        font-size: 1rem;
    }
}
```

**Comment by KleinWang** [comment]
Stylus compiles the "media print" will duplicate the media

**Comment by chharvey** [comment]
(copied from https://github.com/jakubpawlowicz/clean-css/issues/607#issuecomment-230576590)

I'm having the same issue, though I don't know what's causing it.

source:
```css
ul, ol { list-style: none; }
.o-List { padding-left: 0; list-style: none; }
@media screen {
  .o-List-s { padding-left: 0; list-style: none; }
}
@media print {
  .o-List-p { padding-left: 0; list-style: none; }
}

.o-Flex { display: flex; line-height: inherit; justify-content: space-between; }
.o-Flex__Item { flex: 1; }
@media screen {
  .o-Flex-s { display: flex; line-height: inherit; justify-content: space-between; }
  .o-Flex__Item-s { flex: 1; }
}
@media print {
  .o-Flex-p { display: flex; line-height: inherit; justify-content: space-between; }
  .o-Flex__Item-p { flex: 1; }
}

.o-Grid { display: flex; line-height: inherit; flex-wrap: wrap; }
.o-Grid__Item { flex: 100%; }
@media screen {
  .o-Grid-s { display: flex; line-height: inherit; flex-wrap: wrap; }
  .o-Grid__Item-s { flex: 100%; }
}
@media print {
  .o-Grid-p { display: flex; line-height: inherit; flex-wrap: wrap; }
  .o-Grid__Item-p { flex: 100%; }
}
```

actual output (formatting added for readability):
```css
.o-List,
ul,
ol { list-style:none }

.o-Flex,
.o-Grid { line-height:inherit }

.o-List { padding-left:0 }
.o-Flex { display:flex; justify-content:space-between }
.o-Flex__Item { flex:1 }
@media screen {
  .o-List-s { padding-left:0; list-style:none }
  .o-Flex-s { display:flex; line-height:inherit; justify-content:space-between }
  .o-Flex__Item-s { flex:1 }
}
@media print {
 .o-List-p { padding-left:0; list-style:none }
 .o-Flex-p { display:flex; line-height:inherit; justify-content:space-between }
 .o-Flex__Item-p { flex:1 }
}

.o-Grid { display:flex; flex-wrap:wrap }
.o-Grid__Item { flex:100% }
@media screen {
  .o-Grid-s { display:flex; line-height:inherit; flex-wrap:wrap }
  .o-Grid__Item-s { flex:100% }
}
@media print{
 .o-Grid-p { display:flex; line-height:inherit; flex-wrap:wrap }
 .o-Grid__Item-p { flex:100% }
}
```

expected output:
```css
.o-List,
ul,
ol { list-style:none }
.o-List { padding-left:0 }
.o-Flex,
.o-Grid { display:flex; line-height:inherit }

.o-Flex { justify-content:space-between }
.o-Flex__Item { flex:1 }
.o-Grid { flex-wrap:wrap }
.o-Grid__Item { flex:100% }
@media screen {
  .o-Flex-s,
  .o-Grid-s { display:flex; line-height:inherit; }
  .o-List-s { padding-left:0; list-style:none }
  .o-Flex-s { justify-content:space-between }
  .o-Flex__Item-s { flex:1 }
  .o-Grid-s { flex-wrap:wrap }
  .o-Grid__Item-s { flex:100% }
}
@media print {
  .o-Flex-p,
  .o-Grid-p { display:flex; line-height:inherit; }
  .o-List-p { padding-left:0; list-style:none }
  .o-Flex-p { justify-content:space-between }
  .o-Flex__Item-p { flex:1 }
  .o-Grid-p { flex-wrap:wrap }
  .o-Grid__Item-p { flex:100% }
}
```
