### ISSUE TITLE
Merge prefix error

### ISSUE THREAD

**Issue by yisibl** [clean-css/clean-css#700]
## Input

``` css
.foo {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
}
.bar {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  margin: auto;
}

.baz {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
}
```
## Output

``` css
.bar,
.foo {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox
}

.foo {
  display: flex
}

.bar {
  display: flex;
  margin: auto
}

.baz {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex
}
```

:joy: :joy: :joy: 
## Expect

``` css
.foo, .bar, .baz {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex
}

.bar {
  margin: auto
}
```

Used `gulp-minify-css` 1.2.1.
