### ISSUE TITLE
Rules not being merged

### ISSUE THREAD

**Issue by Dylan-Chapman** [clean-css/clean-css#713]
Using through: gulp-minify-css@1.2.2 (has a dependency clean-css@3.4.8)
Options: Doesn't matter (default produces issue)
OS: Windows 7

I'm using Lost for my site's grid system. I also decided to create Bootstrap-esque classes using it.

This is the code that clean-css is operating on:

``` css
.col-xs-1 {
    -webkit-box-flex: 0;
    -webkit-flex: 0 0 auto;
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
    width: calc(99.99% * 1/12 - 13.75px)
}

.col-xs-1:nth-child(n) {
    margin-right: 15px
}

.col-xs-1:last-child,.col-xs-1:nth-child(12n) {
    margin-right: 0
}

.col-xs-2 {
    -webkit-box-flex: 0;
    -webkit-flex: 0 0 auto;
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
    width: calc(99.99% * 2/12 - 12.5px)
}

.col-xs-2:nth-child(n) {
    margin-right: 15px
}

.col-xs-2:last-child, .col-xs-2:nth-child(6n) {
    margin-right: 0
}

/* Goes through .col-xs-12 */
```

However, it does nothing with this code.

I would expect the output to be something akin to:

``` css
.col-xs-1, .col-xs-2 {
    -webkit-box-flex: 0;
    -webkit-flex: 0 0 auto;
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
}

.col-xs-1 {
    width: calc(99.99% * 1/12 - 13.75px)
}

.col-xs-2 {
    width: calc(99.99% * 2/12 - 12.5px)
}

.col-xs-1:nth-child(n), .col-xs-2:nth-child(n) {
    margin-right: 15px
}

.col-xs-1:last-child,.col-xs-1:nth-child(12n), .col-xs-2:last-child, .col-xs-2:nth-child(6n) {
    margin-right: 0
}
```

Is there some reason these aren't being merged?
