### ISSUE TITLE
overflow-wrap minification

### ISSUE THREAD

**Issue by shrpne** [clean-css/clean-css#990]
It is a feature request.
`overflow-wrap` property can be minified to `word-wrap`, as they are aliases, like `::after` minifies to ':after'.

### Environment

* clean-css version - 4.1.9
* node.js version - 8.9.1
* operating system: macOS 10.13.1

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS()
```

### Input CSS

```css
div {overflow-wrap: break-word;}
```

### Actual output CSS

```css
div{overflow-wrap:break-word}
```

### Expected output CSS

```css
div{word-wrap:break-word}
```
